services:
  opensearch:
    image: opensearchproject/opensearch:2.14.0
    environment:
      OPENSEARCH_JAVA_OPTS: -Xms512m -Xmx512m
      DISABLE_INSTALL_DEMO_CONFIG: "true"
      DISABLE_SECURITY_PLUGIN: "true"
      discovery.type: single-node
    ports:
      - "9200:9200"
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:9200 >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.14.0
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
      SERVER_HOST: "0.0.0.0"
    ports:
      - "5601:5601"
    depends_on:
      opensearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:5601/api/status >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    command: ["python", "-m", "ingestion.main"]
    ports:
      - "8000:8000"
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/health', timeout=3)"
        ]
      interval: 5s
      timeout: 5s
      retries: 20
    depends_on:
      opensearch:
        condition: service_healthy

  generator:
    build:
      context: .
      dockerfile: Dockerfile.generator
    command: ["python", "-m", "generator.main"]
    environment:
      SEND_TO_API: "true"
    depends_on:
      opensearch:
        condition: service_healthy
      api:
        condition: service_healthy

  quality:
    build:
      context: .
      dockerfile: Dockerfile.job
    command: ["python", "quality/check_quality.py"]
    depends_on:
      opensearch:
        condition: service_healthy
      api:
        condition: service_started

  analytics:
    build:
      context: .
      dockerfile: Dockerfile.job
    command: ["python", "analytics/aggregate.py"]
    depends_on:
      opensearch:
        condition: service_healthy
      quality:
        condition: service_started
    volumes:
      - ./output:/app/output

volumes:
  opensearch-data:
