apiVersion: v1
kind: ConfigMap
metadata:
  name: event-generator-config
  namespace: liveklass
data:
  GENERATOR_MODE: "prod"
  SEND_TO_API: "true"
  GENERATOR_INTERVAL_SECONDS: "10"
  TOTAL_SESSIONS: "7"
  INVALID_EVENT_PROBABILITY: "0.15"
  GENERATOR_API_URL: "http://ingestion-api.liveklass.svc.cluster.local:8000/events"
