apiVersion: v1
kind: ConfigMap
metadata:
  name: pipeline-config
  namespace: liveklass
data:
  GENERATOR_API_URL: "http://ingestion-api:8000/events"
  GENERATOR_MODE: "prod"
  SEND_TO_API: "true"
  GENERATOR_INTERVAL_SECONDS: "10"
  TOTAL_SESSIONS: "7"
  INVALID_EVENT_PROBABILITY: "0.15"
